Vinay, Bindu | BAH-872 | adding dummy class to fix IT tests (#3)
* Siva, Vinay | Fix build failure due to NoClassDefFoundError for class 'CodedOrFreeText'

This error is obtained due to openMRSWebServicesVersion upgrade.
Corresponding commit
https://github.com/Bahmni/openmrs-module-bahmni.ie.apps/commit/86a89adf1f2979cd0ea1388ed42c9aabb20b13fb

Please find the link for reference related to error
https://talk.openmrs.org/t/java-lang-noclassdeffounderror-org-openmrs-allergen-on-using-webservices-rest-2-14-with-openmrs-1-x/6361/3

* Bindu | Moving the dummy class from src folder to test folder